### PR TITLE
Create tables.sql

### PR DESCRIPTION
**Pull request by alexandre433**
After this new adding of this file, the files under "SQL" should be deleted and only this whould be added.

Why create a file with all the table creation? Easier to add into the database.

### CODE REVIEW

**Comment by Bin4ry1337** [comment]
Its to keep it more structured for people to see that its not malicious.. people were complaining my work were malicious but now they can see its really not.

**Comment by alexandre433** [comment]
Then just change the table's 'Chartset' to 'utf8' because of the output from the database to the website.

**Comment by Bin4ry1337** [comment]
Im not intending to develop or change this CMS anymore, im not giving more of my time to this toxic community, sorry.

**Comment by alexandre433** [comment]
I am just trying to help, nothing else. If others are toxic just ignore them and block. That's it, negativity is supposed to be ignored, if they want to be like that, then be it, fuck them. Just do what you want.

**Review by Bin4ry1337 — COMMENTED** [review]
Will add this. Thanks.

**Pull request closed without merging**
